export const mockQuestsData = [
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh\ntest thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
    {
        name: 'test1',
        description: 'test thôi dì tư, bình tĩnh',
        progress: 0,
        coin: 100,
        ticket: 10,
        max: 5,
        deeplink: '',
    },
]